#!/usr/bin/env bash
#
# Publish minded's Google Play phone screenshots.
#
# What this does:
#   1. Regenerates the canonical screenshots locally (npm run screenshots) so you
#      can review the exact phone set before anything ships.
#   2. Triggers the "Update store screenshots" GitHub Action via `gh`, which
#      regenerates them again in CI and uploads them to Google Play.
#
# Why the upload runs in CI, not here: the Android Publisher API call needs the
# PLAY_SERVICE_ACCOUNT_JSON secret, which lives only in the GitHub `production`
# environment. It is not available locally, so local generation is for REVIEW
# only — the images that actually reach Play are generated by CI.
#
# IMPORTANT: CI generates from the ref you dispatch (default: main), NOT from
# your working tree. If you have UI changes that should appear in the shots,
# merge them to that ref first, or pass --ref <your-branch>.
#
# The run waits for `production` approval in the Actions UI before it publishes;
# that one click can't be done from here.
#
# Usage: extension/scripts/publish-play-screenshots.sh [options]
#   --language <tag>   Play listing language (default: en-US)
#   --ref <branch>     Branch to dispatch the workflow on (default: main)
#   --skip-generate    Don't regenerate/review locally, just trigger the workflow
#   --install          Run `playwright install chromium` before generating
#   --watch            Stream the run with `gh run watch` after dispatch
#   --yes              Skip the confirmation prompt
#   -h, --help         Show this help

set -euo pipefail

WORKFLOW="update-store-screenshots.yml"
LANGUAGE="en-US"
REF="main"
GENERATE=1
INSTALL=0
WATCH=0
ASSUME_YES=0

# The phone set, in the exact order the CI upload script publishes it.
# Keep in sync with PHONE_SCREENSHOT_FILES in .github/scripts/upload-play-screenshots.mjs.
EXPECTED_FILES=(
  dashboard.png
  question-looking-forward.png
  draggable-sun.png
  intent-selection.png
  duration-selection.png
  draggable-moon-dark.png
  intent-selection-dark.png
  duration-selection-dark.png
)

die() {
  echo "error: $*" >&2
  exit 1
}

usage() {
  sed -n '2,30p' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//'
  exit "${1:-0}"
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --language) LANGUAGE="${2:?--language needs a value}"; shift 2 ;;
    --ref) REF="${2:?--ref needs a value}"; shift 2 ;;
    --skip-generate) GENERATE=0; shift ;;
    --install) INSTALL=1; shift ;;
    --watch) WATCH=1; shift ;;
    --yes|-y) ASSUME_YES=1; shift ;;
    -h|--help) usage 0 ;;
    *) die "unknown option: $1 (try --help)" ;;
  esac
done

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
EXTENSION_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
REPO_ROOT="$(git -C "$EXTENSION_DIR" rev-parse --show-toplevel)"
PHONE_DIR="$EXTENSION_DIR/screenshots/google-play/phone"

# --- Preflight ------------------------------------------------------------
command -v gh >/dev/null 2>&1 || die "the GitHub CLI (gh) is not installed."
gh auth status >/dev/null 2>&1 || die "gh is not authenticated. Run: gh auth login"

# --- Generate + review ----------------------------------------------------
if [[ "$GENERATE" -eq 1 ]]; then
  echo "==> Regenerating screenshots locally for review (this can take a few minutes)..."
  if [[ "$INSTALL" -eq 1 ]]; then
    ( cd "$EXTENSION_DIR" && npm run screenshots:install )
  fi
  ( cd "$EXTENSION_DIR" && npm run screenshots )
else
  echo "==> Skipping local generation (--skip-generate)."
fi

echo
echo "Phone screenshots (upload order) in:"
echo "  $PHONE_DIR"
missing=0
for i in "${!EXPECTED_FILES[@]}"; do
  f="${EXPECTED_FILES[$i]}"
  if [[ -f "$PHONE_DIR/$f" ]]; then
    printf '  %d. %s\n' "$((i + 1))" "$f"
  else
    printf '  %d. %s  <-- MISSING\n' "$((i + 1))" "$f"
    missing=1
  fi
done
[[ "$missing" -eq 0 ]] || die "expected phone screenshots are missing (run without --skip-generate)."

echo
echo "Review the images above before publishing. Note: these local files are for"
echo "review only — CI regenerates and uploads its own copy from ref '$REF'."

# --- Confirm --------------------------------------------------------------
if [[ "$ASSUME_YES" -ne 1 ]]; then
  read -r -p "Trigger 'Update store screenshots' (language=$LANGUAGE, ref=$REF)? [y/N] " reply
  [[ "$reply" =~ ^[Yy]$ ]] || die "aborted."
fi

# --- Trigger --------------------------------------------------------------
echo "==> Dispatching workflow..."
gh workflow run "$WORKFLOW" \
  --repo "$(gh repo view --json nameWithOwner -q .nameWithOwner)" \
  --ref "$REF" \
  -f language="$LANGUAGE" \
  -f confirm=true

echo "==> Dispatched. Fetching the run..."
run_url=""
for _ in 1 2 3 4 5; do
  sleep 3
  run_url="$(gh run list --workflow "$WORKFLOW" --branch "$REF" --limit 1 \
    --json url -q '.[0].url' 2>/dev/null || true)"
  [[ -n "$run_url" ]] && break
done

echo
if [[ -n "$run_url" ]]; then
  echo "Run:  $run_url"
else
  echo "Run started — open the Actions tab to find it:"
  echo "  $(gh repo view --json url -q .url)/actions/workflows/$WORKFLOW"
fi

cat <<'NEXT'

Next steps:
  1. Approve the `production` environment in the Actions UI (required — can't be
     done from the CLI).
  2. After it finishes, verify the phone screenshots and their order in Play
     Console.
NEXT

if [[ "$WATCH" -eq 1 && -n "$run_url" ]]; then
  echo
  echo "==> Watching (will sit at 'waiting' until you approve production)..."
  gh run watch "$(basename "$run_url")" || true
fi
