name: Build & Release
on:
  workflow_dispatch:
    inputs: null
  push:
    branches: [main]
  pull_request:
    branches: [main]
#    tags:
#      - v*

defaults:
  run:
    working-directory: ./extension

jobs:
  build-on-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v6
        with:
          node-version: 22
      - name: Check out Git repository
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Get npm cache directory
        id: npm-cache-dir
        run: echo "dir=$(npm config get cache)" >> "$GITHUB_OUTPUT"
      - uses: actions/cache@v5
        id: npm-cache # use this to check for `cache-hit` ==> if: steps.npm-cache.outputs.cache-hit != 'true'
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install npm Packages
        #  if: steps.npm-cache.outputs.cache-hit != 'true'
        run: npm i

      - name: Lint
        run: npm run lint

      - name: Test Unit
        run: npm test

      - name: Build
        run: npm run build

      - name: Pack
        run: npm run pack

      - name: 'Upload Artifact'
        if: github.event_name != 'pull_request'
        uses: actions/upload-artifact@v7
        with:
          name: minded-download
          path: extension/minded.zip
